version: '3.9'

services:
  # Database
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ihjezly-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - ihjezly-network
    restart: unless-stopped

  # Backend API
  api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: ihjezly-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=IhjezlyDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;Encrypt=False;
    volumes:
      - ./certs:/https
    depends_on:
      - db
    ports:
      - "5050:5050"
    networks:
      - ihjezly-network
    restart: unless-stopped

  # Frontend - REMOVED PORT MAPPING
  frontend:
    build:
      context: ./Ihjizely_Admin
      dockerfile: Dockerfile
    container_name: ihjizely-admin
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - ihjezly-network
    depends_on:
      - api
    ports:
      - "8080:80"
      - "8081:443"
    restart: unless-stopped

volumes:
  sql_data:
  caddy_data:
  caddy_config:

networks:
  ihjezly-network:
    driver: bridge