services:
  # Database
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ihjezly-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - ihjezly-network
    restart: unless-stopped

  # Backend API
  api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: ihjezly-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=IhjezlyDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;Encrypt=False;
    depends_on:
      - db
    ports:
      - "5050:5050"
    networks:
      - ihjezly-network
    restart: unless-stopped
    volumes:
      - ./uploads:/app/wwwroot/uploads

  # Frontend with Caddy
  frontend:
    build:
      context: ./Ihjizely_Admin
      dockerfile: Dockerfile
    container_name: ihjizely-admin
    volumes:
      - ./caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - ihjezly-network
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

volumes:
  sql_data:
  caddy_data:
  caddy_config:

networks:
  ihjezly-network:
    driver: bridge