namespace Ihjezly.Domain.Properties;

public enum Facility
{
    GardenView,
    MountainView,
    SeaView,
    Elevator,
    Internet,
    Breakfast,
    PrivateBeach,
    Parking,
    SecurityOffice,
    PropertyFacilities,
    AirConditioning,
    Heating,
    CookingUtensils,
    Microwave,
    WashingMachine,
    Refrigerator,
    Dishwasher,
    Oven,
    Screen,
    MassageChair,
    Kitchen,
    ChildrenToys,
    Sauna,
    PlayStation,
    AccessiblePlaceforPeoplewithDisabilities,
    Jacuzzi,
    AirportPickup,
    SwimmingPool,
    BarbecueCorner,
}